/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : bigint,
  'status' : string,
  'staffId' : bigint,
  'date' : string,
}
export interface Bill {
  'id' : bigint,
  'status' : string,
  'month' : bigint,
  'societyId' : bigint,
  'breakdown' : BillBreakdown,
  'year' : bigint,
  'dueDate' : string,
  'unitId' : bigint,
  'grandTotal' : bigint,
  'unitNumber' : string,
  'previousDue' : bigint,
  'amount' : bigint,
}
export interface BillBreakdown {
  'nonOccupancyCharges' : bigint,
  'interest' : bigint,
  'repairMaintenance' : bigint,
  'serviceCharges' : bigint,
  'otherCharges' : bigint,
  'houseTax' : bigint,
  'liftMaintenance' : bigint,
  'sinkingFund' : bigint,
  'parkingCharges' : bigint,
}
export interface Complaint {
  'id' : bigint,
  'status' : string,
  'residentId' : Principal,
  'title' : string,
  'createdAt' : string,
  'description' : string,
  'resolution' : [] | [string],
  'unitNumber' : string,
  'category' : string,
  'priority' : string,
  'residentName' : string,
}
export interface Expense {
  'id' : bigint,
  'title' : string,
  'societyId' : bigint,
  'paymentMethod' : string,
  'date' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
  'paidBy' : string,
  'paidTo' : string,
  'receiptNumber' : string,
}
export interface FinancialSummary {
  'totalCollected' : bigint,
  'totalBilled' : bigint,
  'pendingDues' : bigint,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'postedAt' : string,
  'postedBy' : string,
  'content' : string,
  'isActive' : boolean,
  'category' : string,
}
export interface Poll {
  'id' : bigint,
  'question' : string,
  'createdAt' : string,
  'createdBy' : string,
  'isActive' : boolean,
  'options' : Array<PollOption>,
}
export interface PollOption { 'id' : bigint, 'votes' : bigint, 'text' : string }
export interface SalaryRecord {
  'id' : bigint,
  'status' : string,
  'month' : bigint,
  'staffId' : bigint,
  'year' : bigint,
  'amount' : bigint,
  'paidOn' : string,
}
export interface SocietyInfo {
  'city' : string,
  'name' : string,
  'registrationNumber' : string,
  'address' : string,
  'contactPhone' : string,
}
export interface Staff {
  'id' : bigint,
  'salary' : bigint,
  'name' : string,
  'role' : string,
  'joiningDate' : string,
  'isActive' : boolean,
  'phone' : string,
}
export interface Tower {
  'id' : bigint,
  'totalFloors' : bigint,
  'name' : string,
}
export interface Unit {
  'id' : bigint,
  'unitType' : [] | [string],
  'towerId' : bigint,
  'floor' : bigint,
  'ownerName' : string,
  'ownerId' : [] | [Principal],
  'area' : [] | [bigint],
  'ownershipType' : [] | [string],
  'memberCount' : [] | [bigint],
  'maintenanceBreakdown' : [] | [UnitBreakdown],
  'email' : [] | [string],
  'isOccupied' : boolean,
  'unitNumber' : string,
  'previousDue' : bigint,
  'phone' : [] | [string],
  'monthlyMaintenance' : bigint,
}
export interface UnitBreakdown {
  'nonOccupancyCharges' : bigint,
  'interest' : bigint,
  'repairMaintenance' : bigint,
  'serviceCharges' : bigint,
  'otherCharges' : bigint,
  'houseTax' : bigint,
  'liftMaintenance' : bigint,
  'sinkingFund' : bigint,
  'parkingCharges' : bigint,
}
export interface UserProfile { 'name' : string, 'unitId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visitor {
  'id' : bigint,
  'status' : string,
  'hostUnit' : string,
  'name' : string,
  'checkInTime' : string,
  'hostUnitId' : bigint,
  'checkOutTime' : [] | [string],
  'phone' : string,
  'purpose' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSalaryRecord' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, string],
    bigint
  >,
  'addStaff' : ActorMethod<[string, string, string, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOutVisitor' : ActorMethod<[bigint, string], undefined>,
  'createBill' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      BillBreakdown,
    ],
    bigint
  >,
  'createComplaint' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'createExpense' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    bigint
  >,
  'createNotice' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createPoll' : ActorMethod<[string, Array<string>, string, string], bigint>,
  'createTower' : ActorMethod<[string, bigint], bigint>,
  'createUnit' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      [] | [Principal],
      boolean,
      bigint,
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [UnitBreakdown],
      bigint,
    ],
    bigint
  >,
  'deleteAllBills' : ActorMethod<[], undefined>,
  'deleteAllExpenses' : ActorMethod<[], undefined>,
  'deleteBill' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteTower' : ActorMethod<[bigint], undefined>,
  'deleteUnit' : ActorMethod<[bigint], undefined>,
  'getActiveVisitors' : ActorMethod<[], Array<Visitor>>,
  'getAttendance' : ActorMethod<[], Array<Attendance>>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getFinancialSummary' : ActorMethod<[], FinancialSummary>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getPolls' : ActorMethod<[], Array<Poll>>,
  'getSalaryRecords' : ActorMethod<[], Array<SalaryRecord>>,
  'getSocietyInfo' : ActorMethod<[], [] | [SocietyInfo]>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getTowers' : ActorMethod<[], Array<Tower>>,
  'getUnits' : ActorMethod<[], Array<Unit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitors' : ActorMethod<[], Array<Visitor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[bigint, string, string], bigint>,
  'recordPayment' : ActorMethod<[bigint, bigint, string], undefined>,
  'registerVisitor' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBill' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      BillBreakdown,
      string,
    ],
    undefined
  >,
  'updateComplaintStatus' : ActorMethod<
    [bigint, string, [] | [string]],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateSocietyInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateTower' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateUnit' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      bigint,
      string,
      [] | [Principal],
      boolean,
      bigint,
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [UnitBreakdown],
      bigint,
    ],
    undefined
  >,
  'voteOnPoll' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];