/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SalaryRecord {
    id: bigint;
    status: string;
    month: bigint;
    staffId: bigint;
    year: bigint;
    amount: bigint;
    paidOn: string;
}
export interface SocietyInfo {
    city: string;
    name: string;
    registrationNumber: string;
    address: string;
    contactPhone: string;
}
export interface Attendance {
    id: bigint;
    status: string;
    staffId: bigint;
    date: string;
}
export interface Poll {
    id: bigint;
    question: string;
    createdAt: string;
    createdBy: string;
    isActive: boolean;
    options: Array<PollOption>;
}
export interface Tower {
    id: bigint;
    totalFloors: bigint;
    name: string;
}
export interface Unit {
    id: bigint;
    towerId: bigint;
    floor: bigint;
    ownerName: string;
    ownerId?: Principal;
    isOccupied: boolean;
    unitNumber: string;
    monthlyMaintenance: bigint;
}
export interface Staff {
    id: bigint;
    salary: bigint;
    name: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    phone: string;
}
export interface Complaint {
    id: bigint;
    status: string;
    residentId: Principal;
    title: string;
    createdAt: string;
    description: string;
    resolution?: string;
    unitNumber: string;
    category: string;
    priority: string;
    residentName: string;
}
export interface Notice {
    id: bigint;
    title: string;
    postedAt: string;
    postedBy: string;
    content: string;
    isActive: boolean;
    category: string;
}
export interface PollOption {
    id: bigint;
    votes: bigint;
    text: string;
}
export interface Bill {
    id: bigint;
    status: string;
    month: bigint;
    year: bigint;
    dueDate: string;
    unitId: bigint;
    unitNumber: string;
    amount: bigint;
}
export interface Visitor {
    id: bigint;
    status: string;
    hostUnit: string;
    name: string;
    checkInTime: string;
    hostUnitId: bigint;
    checkOutTime?: string;
    phone: string;
    purpose: string;
}
export interface FinancialSummary {
    totalCollected: bigint;
    totalBilled: bigint;
    pendingDues: bigint;
}
export interface UserProfile {
    name: string;
    unitId?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSalaryRecord(staffId: bigint, month: bigint, year: bigint, amount: bigint, paidOn: string, status: string): Promise<bigint>;
    addStaff(name: string, role: string, phone: string, salary: bigint, joiningDate: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkOutVisitor(id: bigint, checkOutTime: string): Promise<void>;
    createBill(unitId: bigint, unitNumber: string, amount: bigint, dueDate: string, month: bigint, year: bigint): Promise<bigint>;
    createComplaint(title: string, description: string, category: string, unitNumber: string, residentName: string, priority: string, createdAt: string): Promise<bigint>;
    createNotice(title: string, content: string, category: string, postedBy: string, postedAt: string): Promise<bigint>;
    createPoll(question: string, options: Array<string>, createdBy: string, createdAt: string): Promise<bigint>;
    createTower(name: string, totalFloors: bigint): Promise<bigint>;
    createUnit(towerId: bigint, unitNumber: string, floor: bigint, ownerName: string, ownerId: Principal | null, isOccupied: boolean, monthlyMaintenance: bigint): Promise<bigint>;
    deleteTower(id: bigint): Promise<void>;
    deleteUnit(id: bigint): Promise<void>;
    getActiveVisitors(): Promise<Array<Visitor>>;
    getAttendance(): Promise<Array<Attendance>>;
    getBills(): Promise<Array<Bill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaints(): Promise<Array<Complaint>>;
    getFinancialSummary(): Promise<FinancialSummary>;
    getNotices(): Promise<Array<Notice>>;
    getPolls(): Promise<Array<Poll>>;
    getSalaryRecords(): Promise<Array<SalaryRecord>>;
    getSocietyInfo(): Promise<SocietyInfo | null>;
    getStaff(): Promise<Array<Staff>>;
    getTowers(): Promise<Array<Tower>>;
    getUnits(): Promise<Array<Unit>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitors(): Promise<Array<Visitor>>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(staffId: bigint, date: string, status: string): Promise<bigint>;
    recordPayment(billId: bigint, amount: bigint, paymentMethod: string): Promise<void>;
    registerVisitor(name: string, phone: string, purpose: string, hostUnit: string, hostUnitId: bigint, checkInTime: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateComplaintStatus(id: bigint, status: string, resolution: string | null): Promise<void>;
    updateSocietyInfo(name: string, address: string, city: string, registrationNumber: string, contactPhone: string): Promise<void>;
    updateTower(id: bigint, name: string, totalFloors: bigint): Promise<void>;
    updateUnit(id: bigint, towerId: bigint, unitNumber: string, floor: bigint, ownerName: string, ownerId: Principal | null, isOccupied: boolean, monthlyMaintenance: bigint): Promise<void>;
    voteOnPoll(pollId: bigint, optionId: bigint): Promise<void>;
}
import type { Complaint as _Complaint, SocietyInfo as _SocietyInfo, Unit as _Unit, UserProfile as _UserProfile, UserRole as _UserRole, Visitor as _Visitor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSalaryRecord(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addStaff(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkOutVisitor(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOutVisitor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOutVisitor(arg0, arg1);
            return result;
        }
    }
    async createBill(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createComplaint(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createComplaint(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComplaint(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createNotice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPoll(arg0: string, arg1: Array<string>, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTower(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTower(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTower(arg0, arg1);
            return result;
        }
    }
    async createUnit(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: Principal | null, arg5: boolean, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createUnit(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUnit(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async deleteTower(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTower(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTower(arg0);
            return result;
        }
    }
    async deleteUnit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUnit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUnit(arg0);
            return result;
        }
    }
    async getActiveVisitors(): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveVisitors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveVisitors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendance(): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance();
            return result;
        }
    }
    async getBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaints();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaints();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialSummary(): Promise<FinancialSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummary();
            return result;
        }
    }
    async getNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotices();
            return result;
        }
    }
    async getPolls(): Promise<Array<Poll>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolls();
            return result;
        }
    }
    async getSalaryRecords(): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaryRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaryRecords();
            return result;
        }
    }
    async getSocietyInfo(): Promise<SocietyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocietyInfo();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocietyInfo();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff();
            return result;
        }
    }
    async getTowers(): Promise<Array<Tower>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTowers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTowers();
            return result;
        }
    }
    async getUnits(): Promise<Array<Unit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnits();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnits();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitors(): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async recordPayment(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async registerVisitor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVisitor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVisitor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateComplaintStatus(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, arg1, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, arg1, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSocietyInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocietyInfo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocietyInfo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTower(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTower(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTower(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUnit(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: Principal | null, arg6: boolean, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUnit(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUnit(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async voteOnPoll(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteOnPoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteOnPoll(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Complaint_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Unit_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Unit): Unit {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Visitor_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visitor): Visitor {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocietyInfo]): SocietyInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    unitId: [] | [bigint];
}): {
    name: string;
    unitId?: bigint;
} {
    return {
        name: value.name,
        unitId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.unitId))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    residentId: Principal;
    title: string;
    createdAt: string;
    description: string;
    resolution: [] | [string];
    unitNumber: string;
    category: string;
    priority: string;
    residentName: string;
}): {
    id: bigint;
    status: string;
    residentId: Principal;
    title: string;
    createdAt: string;
    description: string;
    resolution?: string;
    unitNumber: string;
    category: string;
    priority: string;
    residentName: string;
} {
    return {
        id: value.id,
        status: value.status,
        residentId: value.residentId,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        resolution: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.resolution)),
        unitNumber: value.unitNumber,
        category: value.category,
        priority: value.priority,
        residentName: value.residentName
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    towerId: bigint;
    floor: bigint;
    ownerName: string;
    ownerId: [] | [Principal];
    isOccupied: boolean;
    unitNumber: string;
    monthlyMaintenance: bigint;
}): {
    id: bigint;
    towerId: bigint;
    floor: bigint;
    ownerName: string;
    ownerId?: Principal;
    isOccupied: boolean;
    unitNumber: string;
    monthlyMaintenance: bigint;
} {
    return {
        id: value.id,
        towerId: value.towerId,
        floor: value.floor,
        ownerName: value.ownerName,
        ownerId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.ownerId)),
        isOccupied: value.isOccupied,
        unitNumber: value.unitNumber,
        monthlyMaintenance: value.monthlyMaintenance
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    hostUnit: string;
    name: string;
    checkInTime: string;
    hostUnitId: bigint;
    checkOutTime: [] | [string];
    phone: string;
    purpose: string;
}): {
    id: bigint;
    status: string;
    hostUnit: string;
    name: string;
    checkInTime: string;
    hostUnitId: bigint;
    checkOutTime?: string;
    phone: string;
    purpose: string;
} {
    return {
        id: value.id,
        status: value.status,
        hostUnit: value.hostUnit,
        name: value.name,
        checkInTime: value.checkInTime,
        hostUnitId: value.hostUnitId,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.checkOutTime)),
        phone: value.phone,
        purpose: value.purpose
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Unit>): Array<Unit> {
    return value.map((x)=>from_candid_Unit_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visitor>): Array<Visitor> {
    return value.map((x)=>from_candid_Visitor_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    unitId?: bigint;
}): {
    name: string;
    unitId: [] | [bigint];
} {
    return {
        name: value.name,
        unitId: value.unitId ? candid_some(value.unitId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
